targets = [
    "aarch64-linux-android",
    "armv7-linux-androideabi",
    "i686-linux-android",
    "x86_64-pc-windows-gnu",
    "x86_64-unknown-linux-gnu",
]

accepted = [
    "MIT",
    "BSD-3-Clause",
    "0BSD",
    "MIT-Modern-Variant",
    "FTL",
    "OFL-1.1",
    "Zlib",
    "zlib-acknowledgement",
    "MPL-2.0",
    "Apache-2.0",
]

[unicode-ident]
accepted = ["Unicode-DFS-2016"]
