// В rust-sfml забыли реализовать сканкоды
// https://github.com/jeremyletang/rust-sfml/issues/311

use crate::input::ScanCode;
use sfml::window::Key;

impl Into<ScanCode> for Key {
    fn into(self) -> ScanCode {
        match self {
            Key::Space => ScanCode::Space,
            Key::Tilde => ScanCode::Apostrophe,
            Key::Comma => ScanCode::Comma,
            Key::Hyphen => ScanCode::Minus,
            Key::Period => ScanCode::Period,
            Key::Slash => ScanCode::Slash,
            Key::Num0 => ScanCode::Num0,
            Key::Num1 => ScanCode::Num1,
            Key::Num2 => ScanCode::Num2,
            Key::Num3 => ScanCode::Num3,
            Key::Num4 => ScanCode::Num4,
            Key::Num5 => ScanCode::Num5,
            Key::Num6 => ScanCode::Num6,
            Key::Num7 => ScanCode::Num7,
            Key::Num8 => ScanCode::Num8,
            Key::Num9 => ScanCode::Num9,
            Key::Semicolon => ScanCode::Semicolon,
            Key::Equal => ScanCode::Equal,
            Key::A => ScanCode::A,
            Key::B => ScanCode::B,
            Key::C => ScanCode::C,
            Key::D => ScanCode::D,
            Key::E => ScanCode::E,
            Key::F => ScanCode::F,
            Key::G => ScanCode::G,
            Key::H => ScanCode::H,
            Key::I => ScanCode::I,
            Key::J => ScanCode::J,
            Key::K => ScanCode::K,
            Key::L => ScanCode::L,
            Key::M => ScanCode::M,
            Key::N => ScanCode::N,
            Key::O => ScanCode::O,
            Key::P => ScanCode::P,
            Key::Q => ScanCode::Q,
            Key::R => ScanCode::R,
            Key::S => ScanCode::S,
            Key::T => ScanCode::T,
            Key::U => ScanCode::U,
            Key::V => ScanCode::V,
            Key::W => ScanCode::W,
            Key::X => ScanCode::X,
            Key::Y => ScanCode::Y,
            Key::Z => ScanCode::Z,
            Key::LBracket => ScanCode::LeftBracket,
            Key::Backslash => ScanCode::Backslash,
            Key::RBracket => ScanCode::RightBracket,
            Key::Escape => ScanCode::Escape,
            Key::Enter => ScanCode::Enter,
            Key::Tab => ScanCode::Tab,
            Key::Backspace => ScanCode::Backspace,
            Key::Insert => ScanCode::Insert,
            Key::Delete => ScanCode::Delete,
            Key::Right => ScanCode::Right,
            Key::Left => ScanCode::Left,
            Key::Down => ScanCode::Down,
            Key::Up => ScanCode::Up,
            Key::PageUp => ScanCode::PageUp,
            Key::PageDown => ScanCode::PageDown,
            Key::Home => ScanCode::Home,
            Key::End => ScanCode::End,
            Key::Pause => ScanCode::Pause,
            Key::F1 => ScanCode::F1,
            Key::F2 => ScanCode::F2,
            Key::F3 => ScanCode::F3,
            Key::F4 => ScanCode::F4,
            Key::F5 => ScanCode::F5,
            Key::F6 => ScanCode::F6,
            Key::F7 => ScanCode::F7,
            Key::F8 => ScanCode::F8,
            Key::F9 => ScanCode::F9,
            Key::F10 => ScanCode::F10,
            Key::F11 => ScanCode::F11,
            Key::F12 => ScanCode::F12,
            Key::F13 => ScanCode::F13,
            Key::F14 => ScanCode::F14,
            Key::F15 => ScanCode::F15,
            Key::Numpad0 => ScanCode::Kp0,
            Key::Numpad1 => ScanCode::Kp1,
            Key::Numpad2 => ScanCode::Kp2,
            Key::Numpad3 => ScanCode::Kp3,
            Key::Numpad4 => ScanCode::Kp4,
            Key::Numpad5 => ScanCode::Kp5,
            Key::Numpad6 => ScanCode::Kp6,
            Key::Numpad7 => ScanCode::Kp7,
            Key::Numpad8 => ScanCode::Kp8,
            Key::Numpad9 => ScanCode::Kp9,
            Key::Divide => ScanCode::KpDivide,
            Key::Multiply => ScanCode::KpMultiply,
            Key::Subtract => ScanCode::KpSubtract,
            Key::Add => ScanCode::KpAdd,
            Key::LShift => ScanCode::LeftShift,
            Key::LControl => ScanCode::LeftControl,
            Key::LAlt => ScanCode::LeftAlt,
            Key::LSystem => ScanCode::LeftSuper,
            Key::RShift => ScanCode::RightShift,
            Key::RControl => ScanCode::RightControl,
            Key::RAlt => ScanCode::RightAlt,
            Key::RSystem => ScanCode::RightSuper,
            Key::Menu => ScanCode::Menu,
            Key::Unknown => ScanCode::Unknown,
            _ => ScanCode::Unknown,
        }
    }
}
